// Real, self-contained animation cases for the Técnicas page. Each `grid` is an 81-char
// snapshot (taken from an actual puzzle) on which the technique fires when the board is
// re-derived from scratch (naive candidates) — so the diagram needs no hidden context.
// Generated by the (throwaway) src/data/_gen_cases generator and re-verified by
// techniqueCases.test.ts.
import generated from './techniqueCases.generated.json';

export type CellClass = 'hl' | 'peer' | 'elim' | 'place';
export type CellMark = { idx: number; cls: CellClass; d?: number };
export type Frame = { caption: string; cells: CellMark[] };
export type TechniqueCase = { grid: string; frames: Frame[] };

// The JSON widens `cls` to `string`; the data is produced and verified by our own tooling.
export const CASES = generated as unknown as Record<string, TechniqueCase>;
